-- Web funnel (#48): short, unambiguous share slugs on activities so a room has
-- a link (enokiapp.com/r/<slug>). Generated by a BEFORE INSERT trigger so rooms
-- created from mobile OR web both get one, and a single link format serves both.

-- 10-char lowercase slug from an unambiguous base32 alphabet (no 0/o/1/l).
create or replace function public.gen_share_slug()
returns text
language plpgsql
as $$
declare
  alphabet constant text := '23456789abcdefghijkmnpqrstuvwxyz';
  result text := '';
  i int;
begin
  for i in 1..10 loop
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return result;
end;
$$;

alter table public.activities add column if not exists share_slug text;

-- Trigger: fill share_slug on insert if not supplied, with collision retry.
create or replace function public.set_share_slug()
returns trigger
language plpgsql
as $$
declare
  candidate text;
  tries int := 0;
begin
  if new.share_slug is not null then
    return new;
  end if;
  loop
    candidate := public.gen_share_slug();
    exit when not exists (select 1 from public.activities where share_slug = candidate);
    tries := tries + 1;
    if tries > 20 then
      raise exception 'could not generate a unique share_slug after % tries', tries;
    end if;
  end loop;
  new.share_slug := candidate;
  return new;
end;
$$;

drop trigger if exists activities_set_share_slug on public.activities;
create trigger activities_set_share_slug
  before insert on public.activities
  for each row execute function public.set_share_slug();

-- Backfill existing rows (unique per row).
do $$
declare
  r record;
  candidate text;
  tries int;
begin
  for r in select id from public.activities where share_slug is null loop
    tries := 0;
    loop
      candidate := public.gen_share_slug();
      exit when not exists (select 1 from public.activities where share_slug = candidate);
      tries := tries + 1;
      if tries > 20 then
        raise exception 'share_slug backfill failed for %', r.id;
      end if;
    end loop;
    update public.activities set share_slug = candidate where id = r.id;
  end loop;
end $$;

alter table public.activities alter column share_slug set not null;
create unique index if not exists activities_share_slug_key
  on public.activities (share_slug);
